gym:
  patch_size: [128, 128]
  resize_thumbnail: [512, 512]
  max_episode_steps: 1000

train:
  batch_size: 5
  lr: 0.001
  memory_size: 5
  gamma: 0.9
  eps_start: 1
  eps_end: 0.01
  eps_decay: 0.001
  target_update: 10
  
  num_episodes: 5000
  saving_update: 100